version = 1

# Analyse JavaScript / Vue / Nuxt
[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs", "browser"]
  dialect = "typescript" # fonctionne aussi pour JS pur
  style_guide = "airbnb"
  lint_strict = true

# Détection de secrets (API keys, tokens, etc.)
[[analyzers]]
name = "secrets"
enabled = true

# Exclusions pour éviter le bruit inutile
exclude_patterns = [
  "node_modules/**",
  ".nuxt/**",
  ".output/**",
  "dist/**",
  "build/**",
  "*.log",
  "coverage/**"
]
